try prepulling c1 image

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -25,15 +25,9 @@ jobs:
       # Enable blacksmith docker layer caching
       #- uses: useblacksmith/setup-docker-builder@v1
 
-      - name: Install AWS CLI
+      - name: Pre-pull ceramic-one image
         run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip -q awscliv2.zip
-          sudo ./aws/install --update
-
-      - name: Login to AWS ECR Public as a guest # Higher rate limits for pulling from public ECR repositories (ceramic-one)
-        run: |
-          aws ecr-public get-login-password --region us-east-1 --no-sign-request | docker login --username AWS --password-stdin public.ecr.aws
+          docker pull public.ecr.aws/r5b3e0r5/3box/ceramic-one:0.56.0 || echo "Pull failed, will retry during docker-compose"
 
       - name: Run tests
         run:
