skip repo test

diff --git a/.github/workflows/build-repo-server.yaml b/.github/workflows/build-repo-server.yaml
--- a/.github/workflows/build-repo-server.yaml
+++ b/.github/workflows/build-repo-server.yaml
@@ -25,39 +25,39 @@ env:
   DOCKER_BUILDKIT: 1
 
 jobs:
-  build-and-test:
-    runs-on: ubuntu-latest
-    # container:
-    #   image: ubuntu:latest
-    #   options: --user 1001
+  # build-and-test:
+  #   runs-on: ubuntu-latest
+  #   # container:
+  #   #   image: ubuntu:latest
+  #   #   options: --user 1001
 
-    steps:
-      - name: Check out repository
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Check out repository
+  #       uses: actions/checkout@v2
 
-      - name: Set up the environment
-        # Replace this line with the appropriate setup for your project
-        # Examples:
-        uses: actions/setup-node@v2
-        with:
-          node-version: 16
+  #     - name: Set up the environment
+  #       # Replace this line with the appropriate setup for your project
+  #       # Examples:
+  #       uses: actions/setup-node@v2
+  #       with:
+  #         node-version: 16
 
-      - name: Set up docker-compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo docker-compose --version
-          docker info
+  #     - name: Set up docker-compose
+  #       run: |
+  #         sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+  #         sudo docker-compose --version
+  #         docker info
 
-      - name: Install dependencies
-        run: cd desci-repo && yarn
+  #     - name: Install dependencies
+  #       run: cd desci-repo && yarn
 
-      - name: Run tests
-        run: |
-          cd desci-repo && export DOCKER_BUILDKIT=1 && yarn && yarn test
-          echo "exit code $?"
-          if [ $? -ne 0 ]; then
-            exit 1
-          fi
+  #     - name: Run tests
+  #       run: |
+  #         cd desci-repo && export DOCKER_BUILDKIT=1 && yarn && yarn test
+  #         echo "exit code $?"
+  #         if [ $? -ne 0 ]; then
+  #           exit 1
+  #         fi
 
   build-and-push:
     # needs: build-and-test
